### ISSUE TITLE
Is it possible to write exif data previously read to a file?

### ISSUE THREAD

**Issue by richipower** [cdcseacave/TinyEXIF#3]

**Comment by richipower** [comment]
i want for example to read the exif data from a .jpg file, then make some modifications in the .jpg and save a new .jpg file with the exif information in it

**Comment by cdcseacave** [comment]
you are not in the right place, try something like IrfanView, etc

**Comment by richipower** [comment]
i am working with algorithms doing some detections on images, but as well as i can read the exif data from an image (with this tool) i wanted to do the same in the other direction, write my exif data to an image..

**Comment by cdcseacave** [comment]
I understand now. Sorry, there is no support for this currently, and I do not plan to add it as I do not need it personally. Simply copying over the EXIF from the original JPG should be easy, as the EXIF info is just a block of data and just needs to be copied. Feel free to add this functionality.
