### ISSUE TITLE
DLL support seems broken

### ISSUE THREAD

**Issue by levicki** [cdcseacave/TinyEXIF#5]
I compile a DLL by setting `TINYEXIF_EXPORT` macro, and upon linking to it with `TINYEXIF_IMPORT` in another project I am getting a lot of [C4251 warnings](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4251?view=vs-2019) in the following form:
```
'TinyEXIF::EXIFInfo::ImageDescription': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'TinyEXIF::EXIFInfo' (compiling source file ImageCodecJPEG.cpp)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\xstring(4440): message : see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (compiling source file ImageCodecJPEG.cpp)
```
There seem to be two approaches to solving the problem:

1. [Exporting STL Components Inside & Outside of a Class](https://jeffpar.github.io/kbarchive/kb/168/Q168958/)
2. Using dynamic allocation/deallocation of STL structures:

```
class EXPORTED ExportedClass
{
private:
    std::vector<int> *_integers;
public:
    ExportedClass()
    {
        _integers = new std::vector<int>();
    }
    ~ExportedClass()
    {
        delete _integers;
    }
};
```

**Comment by cdcseacave** [comment]
I never tested DLL support, and I do not have any experience with developing for DLL framework. I do not know the best way to fix it, however the intent of this library is to be small and integrated statically in a bigger project. I do not really see a use case for DLL.

**Comment by levicki** [comment]
Usually the use case for DLL is to be able to update just a DLL in case a bug fix is needed instead of recompiling the whole project. Another use case would be if you are developing DLL format plugins for image viewing/editing application. For example you could have JPG, TIFF and say CR2 plugins which all need to read EXIF from those files. Instead of statically linking TinyEXIF to all 3 plugins you can share a single DLL for all of them.

It's not necessary, but it would be nice to have.

In my opinion, the best way to fix it would be to return dynamically allocated info structure and have a matching function that frees said structure. So if you have GetExifInfo() which would return a pointer to a filled structure, you would also have FreeExifInfo() which would deallocate this structure.

**Comment by cdcseacave** [comment]
I see, it makes sens. I'll try that when I find some time.
