### ISSUE TITLE
Error in strrnstr() when compiling with _UNICODE

### ISSUE THREAD

**Issue by levicki** [cdcseacave/TinyEXIF#6]
In the line:
```
				0 == _tcsncmp(haystack, needle, needle_len))
```
You are using TCHAR-ized name of the `strncmp()` function assuming that the project will always be compiled with multi-byte strings. This results in the compile error when the project is compiled with UNICODE support.

That's not the only place where this happens and frankly I don't see a point of using those names if the resst of the code uses std::string which is `char *`, not `wchar_t *`.

**Comment by cdcseacave** [comment]
I agree, this project was never developed with the intention to support UNICODE, and for sure never tested. I also do not plan to ever add it. So I see 2 solutions, either use the non-UNICODE mode, or feel free to add support for UNICODE.

**Comment by cdcseacave** [comment]
I never tested this project with UNICODE, and I do not know how easy is to make it work with it. If you have experience with UNICODE and EXIF, I could use your help to fix it.

**Comment by levicki** [comment]
@cdcseacave I was not asking for you to support UNICODE, just for code consistency.

If the code doesn't support UNICODE, then it should not use `_tcs` macros because that will break in UNICODE projects (_tcslen becomes _wcslen instead of strlen for example). If you ask me, I would just replace `_tcs` with `_str` everywhere and be done with it.

If, on the other hand, you are interested in supporting UNICODE, bear in mind that it is not an easy task -- as far as I am aware Windows uses UCS-2 (2-byte) encoding, while Linux uses UTF-8. Supporting both with the same architecture could be tricky.

**Comment by cdcseacave** [comment]
Good to know, thank you! I am not sure if it even makes much sens supporting unicode as EXIF format might not support it. Though there might be some custom fields that could be in any format.

**Comment by poxiao2** [comment]
I have the same problem then I replace the "_tcs" with "_str", it really worked.

**Comment by levicki** [comment]
Not sure why you would call `strcasecmp()` and rely on a wrapper instead of calling `_stricmp()` directly, Microsoft Visual C++ [does support it](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stricmp-wcsicmp-mbsicmp-stricmp-l-wcsicmp-l-mbsicmp-l?view=msvc-160).

Also, while this does fix the Unicode build, it does absolutely nothing to support EXIF comments which can be encoded with different encodings:

![image](https://user-images.githubusercontent.com/16415478/112724707-eb9d3b00-8f14-11eb-93a4-a77aff6a731e.png)

Image taken from [EXIF specification 2.2](https://www.exif.org/Exif2-2.PDF).

**Comment by cdcseacave** [comment]
@levicki feel free to provide a PR with the improvements you suggest, and pls keep in mind this library should still work in all major OSs, like Windows, Linux, Andoid, Mac and iOS; thanks
