### ISSUE TITLE
Example impractical for large images

### ISSUE THREAD

**Issue by remster** [cdcseacave/TinyEXIF#7]
The example usage suggests to gulp up the entire file:
```
	std::ifstream file(argv[1], std::ifstream::in|std::ifstream::binary);
	file.seekg(0,std::ios::end);
	std::streampos length = file.tellg();
	file.seekg(0,std::ios::beg);
	std::vector<uint8_t> data(length);
	file.read((char*)data.data(), length);
```
This is impractical for large files - and many of us deal with very large images (like 360 panoramas easily exceeding 20MB). I have just spent ~2hrs studying JPEG format to assure myself APP1 segment can only live before the SOS and that - with way less confidence - that APP0 and APP1 must immediately follow SOI (which yields the max offset of 120kB instead of the whole image). Studying jpeg is precisely what tinyexif should relieve users from needing to do. It would be a massive favour if the authors, certainly knowledgeable in JPEG innards, have fixed the example usage with this subtlety in mind.

**Comment by cdcseacave** [comment]
Thx @remster, you are right, this can be improved. I'd be happy to do it, but I do not have time. Anybody in the community want to help?
